// The protocol between an app and a trieur server.
//
// One file, imported by both sides: the client (`remote.ts`) and the server
// (`@trieur/server`) cannot drift apart without TypeScript saying so.
//
// Two structural decisions:
//
// - **An event carries an `id`.** The client can replay its queue after a network outage
//   without risking learning the same filing twice: the server ignores an id it has already
//   seen. Without that, a single unlucky reconnection permanently skews the model.
// - **An event carries the features *and* the text.** Features are enough for the sparse
//   models; the text only serves the embeddings, server-side. Carrying it now avoids having
//   to change the protocol the day a vector model is plugged in — and it stays optional.

import type { Feature, ModelJSON, Ranked, Stats } from './types.js';

export const API_VERSION = 'v1';

export interface SortEvent {
  /** unique id, generated by the client — this is what makes replaying harmless */
  id: string;
  features: Feature[];
  target: string;
  /** negative means an undo */
  weight: number;
  at: number;
  /** what the model had suggested, so the server can measure how right it was */
  predicted?: string | null;
  /** raw text of the card, for embeddings; optional */
  text?: string;
}

export interface PushRequest {
  events: SortEvent[];
}
export interface PushResponse {
  accepted: number;
  /** skipped because already seen */
  duplicates: number;
  version: number;
}

export interface ModelResponse {
  version: number;
  /** null when the client is already up to date (`?since=`) */
  model: ModelJSON | null;
  stats: Stats;
}

export interface PredictRequest {
  features: Feature[];
  targets: string[];
  text?: string;
}
export interface PredictResponse {
  ranked: Ranked[];
  /** which models voted: `sparse+embeddings` */
  source: string;
}

export interface ErrorResponse {
  error: string;
}

/** The routes, built in the same place on both sides. */
export const routes = {
  events: (deck: string) => `/${API_VERSION}/decks/${encodeURIComponent(deck)}/events`,
  model: (deck: string) => `/${API_VERSION}/decks/${encodeURIComponent(deck)}/model`,
  predict: (deck: string) => `/${API_VERSION}/decks/${encodeURIComponent(deck)}/predict`,
  stats: (deck: string) => `/${API_VERSION}/decks/${encodeURIComponent(deck)}/stats`,
};

/** Event id. `crypto.randomUUID` wherever it exists, a fallback otherwise. */
export function eventId(): string {
  const c = globalThis.crypto;
  if (c?.randomUUID) return c.randomUUID();
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
